import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";

import "react-toastify/ReactToastify.min.css";
import "./globals.css";

import Breadcrumbs from "@/core/Breadcrumbs/Breadcrumbs";
import Footer from "@/core/Footer/Footer";
import Header from "@/core/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Open planet",
  description: "Generated by create next app",
  openGraph: {
    title: "Open planet",
    description: "Generated by create next app",
    url: "http://localhost:3000/",
    siteName: "Open planet",
    locale: "en-US",
    type: "website",
  },
  alternates: {
    canonical: "http://localhost:3000/",
  },
};

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  const messages = await getMessages();
  unstable_setRequestLocale(lang);

  return (
    <html lang={lang}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main>
            <Breadcrumbs />
            {children}
          </main>
          {/* <Footer /> */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
